config/routes.rb
Rails.application.routes.draw do
  resources :sightings
  resources :animals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/animals/index'
end

app/models/animal.rb
class Animal < ApplicationRecord
      has_many :sightings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sighting.rb
class Sighting < ApplicationRecord
      belongs_to :animal
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
    def index
        @animals = Animal.all
    end
    
    def new
        # go to Add Animal Page
        @animal = Animal.new
    end
    def create
        @animal = Animal.new(animal_params)
        if @animal.save
            redirect_to animals_path
        else
            render action: :new
        end
    end
    
    def update
        @animal = Animal.find(params[:id])
        if @animal.update_attributes(animal_params)
            redirect_to animals_path
        else
            render :edit
        end
    end
    def edit
        @animal = Animal.new
    end
    
    def destroy
        @animal = Animal.find(params[:id])
        @animal.destroy
        redirect_to animals_path
    end
    
    private
    
    def animal_params
        params.require(:animal).permit(:name, :latin_name, :kingdom)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
    def index
        @animals = Animal.all
    end

    def show
        @animal = Animal.find(params[:id])
        @sightings = Sighting.where(animal_id: params[:id])
    end
    
    def new
        # go to Add Sighting Page
        @id = params[:format]
        @sighting = Sighting.new
    end
    def create
        @sighting = Sighting.new(sighting_params)
        if @sighting.save
            redirect_to animals_path
        else
            render action: :new
        end
    end
    
    def edit
        @sighting = Sighting.new
    end
    def update
        @sighting = Sighting.find(params[:id])
        if @sighting.update_attributes(sightings_params)
            redirect_to animals_path
        else
            render :update
        end
    end
    
    def destroy
        @sighting = Sighting.find(params[:id])
        @sighting.destroy
        render :show #redirect_to sighting_path
    end
    
    private
    
    def sightings_params
        params.require(:sighting).permit(:time, :date, :latitude, :longitude)
    end
    
    def sighting_params
        params.require(:sighting).permit(:time, :date, :latitude, :longitude, :animal_id)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sightings_helper.rb
module SightingsHelper
end

app/views/animals/edit.html.erb
<h1>Edit Animal</h1>

<%= form_for @animal, url: animal_path ,method: :put do |f| %>
<%= f.label :name %>
<%= f.text_field :name %> </br>

<%= f.label :latin_name %>
<%= f.text_field :latin_name %> </br>

<%= f.label :kingdom %>
<%= f.text_field :kingdom %> </br>

<%= f.submit 'Update Animal'%>
<% end %>

app/views/animals/index.html.erb
<h1>Welcome to ANIMAL TRACKER 3000.  Get ready to hunt some aminals.</h1>
<% if @animals.present? %>
    <% @animals.all.each do |animal| %>
        Common Name: <%= animal.id%> <%= animal.name %>.  Latin Name: <%= animal.latin_name %>.  Kingdom: <%= animal.kingdom %> 
        <%= link_to "Update", edit_animal_path(animal) %> <%= link_to "Delete", animal_path(animal), method: :delete %>
        <%= link_to "Sightings", sighting_path(animal), method: :get %><br/>
    <%end%>
<%end%>

<form action="/animals/new" method="get">
    <input type="submit" value="Add Animal" />
</form>

app/views/animals/new.html.erb
<h1>Add New Animal</h1>

<%= form_for @animal do |f| %>
<%= f.label :name %>
<%= f.text_field :name %> </br>

<%= f.label :latin_name %>
<%= f.text_field :latin_name %> </br>

<%= f.label :kingdom %>
<%= f.text_field :kingdom %> </br>

<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WildlifeTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sightings/edit.html.erb
<h1>Edit Sighting</h1>

<%= form_for @sighting, url: sighting_path ,method: :put do |f| %>
<%= f.label :time %>
<%= f.time_field :time %> </br>

<%= f.label :date %>
<%= f.date_field :date %> </br>

<%= f.label :latitude %>
<%= f.text_field :latitude %> </br>

<%= f.label :longitutde %>
<%= f.text_field :longitude %> </br>

<!--<%= f.hidden_field :animal_id, :value => @id %>-->

<%= f.submit 'Update Sighting'%>
<% end %>

app/views/sightings/index.html.erb
<h1>Welcome to ANIMAL TRACKER 3000- Sightings.  Get ready to sight some aminals.</h1>
<!--<% if @animals.present? %>-->
<!--    <% @animals.animal_id.all.each do |animal| %>-->
<!--        Common Name: <%= animal.id%> <%= animal.name %>.  Latin Name: <%= animal.latin_name %>.  Kingdom: <%= animal.kingdom %> -->
<!--        <%= link_to "Update", edit_animal_path(animal) %> <%= link_to "Delete", animal_path(animal), method: :delete %><br/>-->
<!--    <%end%>-->
<!--<%end%>-->

<form action="/animals/new" method="get">
    <input type="submit" value="Add Animal" />
</form>

app/views/sightings/new.html.erb
<h1>Add New Sighting</h1>

<%= form_for @sighting do |f| %>
<%= f.label :time %>
<%= f.time_field :time %> </br>

<%= f.label :date %>
<%= f.date_field :date %> </br>

<%= f.label :latitude %>
<%= f.text_field :latitude %> </br>

<%= f.label :longitutde %>
<%= f.text_field :longitude %> </br>

<%= f.hidden_field :animal_id, :value => @id %>

<%= f.submit %>
<% end %>

app/views/sightings/show.html.erb
<h1>Welcome to ANIMAL TRACKER 3000- Sightings.  Get ready to sight some aminals.</h1>
<% if @sightings.present? %>
    <% @sightings.all.each do |sighting| %>
        <%= sighting.id%> <%= sighting.animal_id %> Date: <%= sighting.date %>.  Time: <%= sighting.time %>.  Latitude: <%= sighting.latitude %>. Longitude: <%= sighting.longitude %> 
        <%= link_to "Update", edit_sighting_path(sighting) %> <%= link_to "Delete", sighting_path(sighting), method: :delete %><br/>
    <%end%>
<%end%>
<%= link_to "Add Sighting", new_sighting_path(@animal)%>